name: Export from Eviroment
on: 
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: 'LCP'
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: /out
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: /solution
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solution

env:
  ENVIRONMENT_URL: 'https://org76bbc37c.crm4.dynamics.com'
  CLIENT_ID: '27a22a77-62a2-483d-bfef-f3075b56a587'
  TENANT_ID: '23e3e3e1-fbfa-4df4-bc07-16b806733ae7'
permissions:
  contents: write  

jobs:
  build:
    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest , windows-latest
    
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1.5.2

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1.5.2
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.CLIENTSECRET }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1.5.2
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Commit Unpack Solution
      run: |
        cp -r ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }} ./${{ github.event.inputs.solution_folder}} 
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git add --all 
        git commit -m "Updates Unpack Solution"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push

    - name: Canvas unpack and Commit
      run: |
        dir
        ${{ env.POWERPLATFORMTOOLS_PACPATH }} canvas unpack --msapp "${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}/CanvasApps/wgj_lcplistcopypasteapp_5f169_DocumentUri.msapp" --sources "${{ github.workspace }}/sources"
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git add --all 
        git commit -m "Updates unpack Canvas Solution"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
